### ISSUE TITLE
redirects thrown in the __root beforeLoad aren't showing the correct route on first-load

### ISSUE THREAD

**Issue by maksymskuibida** [TanStack/router#1534]
### Describe the bug

I am facing an issue on admin panel I am developing now. Sometimes, I cannot find exact steps to reproduce it just returns nothing in Outlet. I checked all my code tree and there is no chance it is bug in my code. Then I reload the page and then I am facing the next issue. beforeLoad of my $lang route is called before __root.tsx beforeLoad what causes other bugs

### Your Example Website or App

admin.7loc.com

### Steps to Reproduce the Bug or Issue

If you want, you can 
1) register here,
2) create profile in form 
3) Navigate between pages on phone or with efficiency slowed down x6 + mobile mode in devtools

### Expected behavior

1) When I am on some route, and there is some content, Outlet have to return it always
2) __root.tsx beforeLoad should be called before other routes beforeLoad as well, as any parent beforeLoad should be called before beforeLoad of any children

### Platform

- OS: It happens more often on phone or if I slow dows processor x6 in browser devtools
- Browser: all
- Version: 1.30.1—1.31.2

**Comment by tannerlinsley** [comment]
Please try with the latest version

Tanner Linsley

**Comment by maksymskuibida** [comment]
1.31.2 is last available version. I am currently on it and it also happens. 
As __root beforeLoad is called before my $lang's beforeLoad when I try to use variable from context, which I return from __root beforeLoad, it is undefined. I use this variable to change lang in params, if it was changed, for example, in user object. So, I set undefined to params, what causes infinite pending state. I reload page, undefined is replacing to actual lang, but I don't know why it also falls into infinite pending and only if I reload the page for third time, it starts working. I fixed it a little bit by checking for if (variable) in $lang beforeLoad, so now when Outlet returns nothing, I reload the page and it works from first reload, but the issue with calling other routes beforeLoad before __root beforeLoad still exists. And issue with Outlet returns nothing still exists. 

Anyway thank you for your hard work on this project. You are doing a lot and present fixes so quick. I beleive issues will be fixed soon, because without this bugs it is perfect router

**Comment by BourqueCharles** [comment]
@maksymskuibida By any chance, are you using redirects in your beforeLoad? I had an issue similar to your's and changing the redirect function to using the navigate function "fixed" those issues.

**Comment by maksymskuibida** [comment]
@BourqueCharles Yes, I am. But this issue happens when I do no redirects. It is interesting, but on my mac it happened may be one or two times. But on my phone in happens almost every time I just navigate between my pages. Outlet returns nothing, so, I see only my layout, but content of current page is empty, I reload the page, and than I am facing an issue that __root beforeLoad called later. My __root beforeLoad returns computedLang, and $lang route have to redirect for it, if it is different from current. For example, if user changed language somwhere else, or somebody followed incorrect link with something incorrect instead of lang. The reason why I compute lang there is because I also use it in not found route(if somebody follows just admin.7loc.com link). I fixed id by checking for a value before redirect and also I could try to make some function for it and instead of using context, call function (which fetches data using query from backend, like user, to obtain current language). Now I am checking for a value and it works fine

But it is still not OK, that 
1) Outlet returns nothing
2) __root beforeLoad is called after routes beforeLoads.

**Comment by alexhanga** [comment]
https://stackblitz.com/edit/github-shdycb-6awa91?file=src%2Froutes%2Findex.tsx

**Comment by alexhanga** [comment]
This bug is related to situation that current route `/` can be used as a layout for new route, so it is not unmounted and router doesn't understand that it should change the layout.

After the page reload router understands that it should use different layout and doesn't use route from `/`

**Comment by maksymskuibida** [comment]
@tannerlinsley @SeanCassiere My issue still now fixed. It is not redirects in my case. It is just Links. I press on link and outlet renders nothing. My layout route is rendered, but routes under it is not. And it happens only on my phone or if I slowdown performance x6. I just navigating by links in my sidebar

https://github.com/TanStack/router/assets/57814533/678687ff-4eff-409f-ab6e-49c2d61464de

**Comment by maksymskuibida** [comment]
Also it happens only one time per route per page load. So, I reloaded the page. After it every route have this issue. But if I press second time for same route, or press, for example categories and then go back to stores issue also disappears

**Comment by maksymskuibida** [comment]
I also tried to remove almost all content for this pages, leave just background and HELLO WORLD and the issue still exists. But it exists only with CPU slowdown x6 and on my phone (samsung a54). It also exists with CPU slowdown x4, but more randomly

**Comment by SeanCassiere** [comment]
Reopening this for now. I've tested this without some layout routes and I can recreate this.

@maksymskuibida please give us a workable reproduction of this. Without a reproduction, it's hard to pinpoint the setup you've got going on and understand what is breaking this for you.

You can create a reproduction quickly on Stackblitz using the [Router file-based starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based).

**Comment by andrii-petlovanyi** [comment]
@SeanCassiere 

I faced the same problem (as in @maksymskuibida ) in my project. I updated to the latest version but it didn't help ..(

**Comment by SeanCassiere** [comment]
> I faced the same problem (as in @maksymskuibida ) in my project. I updated to the latest version but it didn't help ..(

Same as my comment above over [here](https://github.com/TanStack/router/issues/1534#issuecomment-2090007926), need a reproduction.

**Comment by maksymskuibida** [comment]
I will try to give you a reproduction for this. But I also cannot find what actually cause this. it works on my mac m3pro, but if I slowdown CPU it does not work. And also it does not work on my samsung a54, which is not very powerful, but also it is not slow device, so, I don't know what actually cause this

> Reopening this for now. I've tested this without some layout routes and I can recreate this.
> 
> @maksymskuibida please give us a workable reproduction of this. Without a reproduction, it's hard to pinpoint the setup you've got going on and understand what is breaking this for you.
> 
> You can create a reproduction quickly on Stackblitz using the [Router file-based starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based).

**Comment by maksymskuibida** [comment]
@SeanCassiere I am not able to make minimal reproductable example. I am facing this on my real app, but I cannot reproduce it in small example. It would be perfect, if you can share your recreation, so I can test is the same, as my issue on real app

**Comment by maksymskuibida** [comment]
@SeanCassiere But, if it can help, I can make test account on my production app and give you credentials to test it there. Probably it could also help with undefined context issue #1531

**Comment by SeanCassiere** [comment]
@maksymskuibida The reason I'm asking for a reproduction of this issue is that I suspect it comes down to how you've configured your routes and what kind of work is happening in those routes. When testing this out using 6x CPU throttling on the **layout routes** section of the *basic file-based* example, it doesn't surface the issue, so I'm leaning towards it being something specific happening in your app which we haven't expected.

Us seeing the issue happening in your app isn't too helpful for us, since we wouldn't know what the actual configuration was and if there are any unexpected side effects which we haven't considered that are in play here. Or if it's simply a misconfiguration that was allowed in the earlier versions, but not anymore.

Your reproduction doesn't have to be a duplication of the entire app, just the way you've set up the children and the triggering of the navigation of the affected layouts. Without it, we are essentially playing a guessing game as to what's specifically affecting you.

@tannerlinsley do you have any clue as to what's happening, based on the video above?

**Comment by maksymskuibida** [comment]
I checked react tree when issue happens(first video) and then I reloaded the page and issue gone(video 2)
For some reason there is Outlet(video 1) in react tree, instead of Component(video 2)

https://github.com/TanStack/router/assets/57814533/27ab2e8b-a5e1-4748-ae36-f6141973de3c

https://github.com/TanStack/router/assets/57814533/83c8c9db-80bc-4fc0-a581-127c2c83bda2

**Comment by SeanCassiere** [comment]
Copied your route-layout in this stackblitz example (using latest): https://stackblitz.com/edit/github-tluew2?file=src/routes/$lang._authorized.$profileId.lazy.tsx:L19

Could you check and make sure the path params are being passed around correctly? That's one of the only ways I could think of maybe breaking the Router by rendering the same route twice that could bork the Router.

That was the only thing I could see that'd cause any problems.

**Comment by maksymskuibida** [comment]
I checked example you've done. But it have profile/checkout page. My pages, which I havigate between is simple as stores one. They are the same, only have differences inside. Your example works on my phone and with CPU slowdown. The only reason why I started testing CPU slowdown is that my app works on mac and does not work on phone. So, I found that it is not a platform issue, because CPU slowdown on mac also makes this issue happens

**Comment by maksymskuibida** [comment]
Params looks like my, only difference that I have parseParams to ensure profileId is number and to make typescript work good. I use it with useQuery, so, I have this router configuration

```
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen.ts";
import DefaultErrorComponent from "./DefaultErrorComponent.tsx";

export const router = createRouter({
	routeTree,
	context: {
		auth: undefined!,
		queryClient: undefined!,
		showAppAlert: undefined!,
	},
	defaultPreload: "intent",
	defaultPreloadStaleTime: 0,
	defaultErrorComponent: DefaultErrorComponent,
});

// Register the router instance for type safety
declare module "@tanstack/react-router" {
	// noinspection JSUnusedGlobalSymbols
	interface Register {
		router: typeof router;
	}
}
```


I also navigates between pages by using just links. I have any clue what can cause this issue

**Comment by maksymskuibida** [comment]
I cannot share code here, but, by any chance, if you have time, probably we can make google meet, so I can show you my routes configurations and all you need

**Comment by maksymskuibida** [comment]
@tannerlinsley @SeanCassiere I managed to find out what causes an issue. It is lazy routes in combination with loaders, so, when you have both route.ts and route.lazy.tsx. And I managed to create reproductable example. It happens not every time in my example, unlike my app, but in few attempts it is possible to catch it. It looks like that sometimes lazy route file does not load in time and route thinks that there is no component and renders outlet. It is just the same as in my videos above, when Outlet rendered instead of route's component. But in my example it is easier to reproduce an issue with both CPU and network slowed down, may be due to smaller project size. So, here is my stackblitz: https://stackblitz.com/edit/github-klgefm-zvib9i?file=src%2Fmain.tsx.


To reproduce
1) Make sure you are on the home or about page
2) Reload the page.
3) Go to posts
4) Pick a post
5) Press tab1 or tab2 below
6) If issue does not happen, make this steps again. I need 1-3 attempts to make this issue happen

**Comment by maksymskuibida** [comment]
It is also easier to work with issue if you open stackblitz preview in separated browser tab

**Comment by maksymskuibida** [comment]
I also found out that removing 
```
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
```
in router configuration make this issue not to happen

**Comment by maksymskuibida** [comment]
So, the issue happens with defaultPreload: "intent", routes, that have both route.ts and route.lazy.tsx and slow internet/device. 

Probably router does not wait until lazy route loaded and "thinks" that there is no component defined for router

**Comment by maksymskuibida** [comment]
@SeanCassiere @tannerlinsley whay is about this issue? I have provided reproduction above in comment, but the issue still has information needed label

**Comment by SeanCassiere** [comment]
@maksymskuibida label has been changed 👍🏼

**Comment by maksymskuibida** [comment]
Thank you very much. I am very waiting for this fix, as it is, together with undefined context, are only issues I have with tanstack router now. In any other aspect, it is a perfect framework

**Comment by maksymskuibida** [comment]
@SeanCassiere @tannerlinsley I have just updated to the latest version, as I saw that something with lazy was changed in 1.31.27(looks not 100% related), but this issue still happens. Outlet still appears instead of Component. Did you have any change to check it?

**Comment by maksymskuibida** [comment]
Unfortunately, I had to remove lazy routes usage and it works fine, but I would love to come back to using it, once this issue fixed

**Comment by SeanCassiere** [comment]
> @tannerlinsley @SeanCassiere I managed to find out what causes an issue. It is lazy routes in combination with loaders, so, when you have both route.ts and route.lazy.tsx. And I managed to create reproductable example. It happens not every time in my example, unlike my app, but in few attempts it is possible to catch it. It looks like that sometimes lazy route file does not load in time and route thinks that there is no component and renders outlet. It is just the same as in my videos above, when Outlet rendered instead of route's component. But in my example it is easier to reproduce an issue with both CPU and network slowed down, may be due to smaller project size. So, here is my stackblitz: https://stackblitz.com/edit/github-klgefm-zvib9i?file=src%2Fmain.tsx.
> 
> To reproduce
> 
> 1. Slowdown CPU x6, disable cache, slowdown network as slow 3G
> 2. Make sure you are on the home or about page
> 3. Reload the page.
> 4. Go to posts
> 5. Pick a post
> 6. Press tab1 or tab2 below
> 7. If issue does not happen, make this steps again. I need 1-3 attempts to make this issue happen

Still haven't had the stretch of time needed to go through this one. Leaving this open for anyone who's able to look at it.
#1638 looks to possibly be related.

**Comment by maksymskuibida** [comment]
@SeanCassiere I have just tested it on the latest version. I also tested it without CPU reducing, but with turned off cache and network reduced and it also happens

**Comment by noah-franklin** [comment]
I also ran into this issue, sometimes when I navigated to a route for the first time, the outlet in the root route would be empty. I also am using a combination of routes with lazy components and non lazy loaders. Thank you @maksymskuibida 
the removal of defaultPreload: "intent" worked for me.

**Comment by reihwald** [comment]
Just a +1

I'm struggling with the same issue. I can reliably reproduce it even without CPU throttling, I only need to throttle the network to trigger this (a slower development build is sometimes even enough) as I just need to wait for the preloading to start and to click the link before it's finished. It's a real bummer.

**Comment by maksymskuibida** [comment]
the same as @reihwald. It happens time to time on my phone on production build. early on development build on mac and also with "slow 3G" network in devtools

**Comment by maksymskuibida** [comment]
It looks like router has some max wait time for loading files and if it is not loaded in this time window, it renders empty Outlet instead of my Component

**Comment by macalinao** [comment]
+1 here too-- I'm having the same issue with deeply nested lazy routes

**Comment by dimahinev** [comment]
me too

**Comment by AdrianLsk** [comment]
I ran into this issue as well when my cypress tests started to fail after a change from createRoute to createLazyRoute. I am migrating a legacy project using manual code-splitting.

It happens when I define my routes following the pattern from [documentation examples](https://tanstack.com/router/latest/docs/framework/react/guide/code-splitting#code-based-splitting)

```
// src/posts.tsx
export const Route = createLazyRoute('/posts')({
  component: MyComponent,
})

function MyComponent() {
  return <div>My Component</div>
}
```

and 

```
// src/app.tsx
const postsRoute = createRoute({
  getParent: () => rootRoute,
  path: '/posts',
}).lazy(() => import('./posts').then((d) => d.Route))
```

My workaround was to remove createLazyRoute and load the component lazily with createRoute and [lazyRouteComponent](https://tanstack.com/router/latest/docs/framework/react/api/router/lazyRouteComponentFunction#lazyroutecomponent-options)

**Comment by macalinao** [comment]
> I ran into this issue as well when my cypress tests started to fail after a change from createRoute to createLazyRoute. I am migrating a legacy project using manual code-splitting.
> 
> 
> 
> It happens when I define my routes following the pattern from [documentation examples](https://tanstack.com/router/latest/docs/framework/react/guide/code-splitting#code-based-splitting)
> 
> 
> 
> ```
> 
> // src/posts.tsx
> 
> export const Route = createLazyRoute('/posts')({
> 
>   component: MyComponent,
> 
> })
> 
> 
> 
> function MyComponent() {
> 
>   return <div>My Component</div>
> 
> }
> 
> ```
> 
> 
> 
> and 
> 
> 
> 
> ```
> 
> // src/app.tsx
> 
> const postsRoute = createRoute({
> 
>   getParent: () => rootRoute,
> 
>   path: '/posts',
> 
> }).lazy(() => import('./posts').then((d) => d.Route))
> 
> ```
> 
> 
> 
> My workaround was to remove createLazyRoute and load the component lazily with createRoute and [lazyRouteComponent](https://tanstack.com/router/latest/docs/framework/react/api/router/lazyRouteComponentFunction#lazyroutecomponent-options)

Thanks for sharing your workaround. I'll try it on my codebase-- hope it works!

**Comment by aleksolutions** [comment]
I can confirm that using "lazyRouteComponent" instead of .lazy works fine with preLoad: 'intent'.

I didn't know that this exist, and I find it a better approach since I don't have to have a separate "Route" function in the component.

Has this any caveats to be aware of?

**Comment by sepirak-nick** [comment]
+1 experiencing this issue. I also get some weird performance issues, CSS hover transitions for example drop a few frames when attempting to load lazy loaded routes that have a loader.

**Comment by ArmandRedgate** [comment]
I can also confirm I get this issue, as I have been fighting it for weeks.

First I thought it was an issue with loaders, then I tried both file and code-based splitting.

For me, I can reproduce it 100% of the time by simply slowing down my network using the Chrome DevTools throttling feature

![image](https://github.com/TanStack/router/assets/93141585/87a6d1e5-70be-4697-ae1e-cc68f4121d65)

After reading this thread, I can also confirm that removing intent-based loading solved the problem for me, at the cost of a great feature 🥲.

**Comment by sepirak-nick** [comment]
This is also a regression since 1.28.0, since it was working properly back then. This only became an issue for me when upgrading my version in order to take advantage of some new features.

**Comment by sepirak-nick** [comment]
I think this might have been fixed today, in v1.42.0. It seems to be loading fine now, possibly with a flash of empty rendering but that could also just be my configuration.

**Comment by samuelili** [comment]
@sepirak-nick I've been having very similar issues with my project and upgrading to v1.42.0 also seems to have fixed it for me!

**Comment by vinnymeller** [comment]
just adding another one, been having this issue & lurking this thread. updated after seeing above comments and seems to be fixed :smile:

**Comment by ArmandRedgate** [comment]
I've upgraded to v1.42.0 and, while I am no longer stuck with nothing rendering even after all lazy loaded components are fetched, I do still have a worse experience than with intent-based loading turned off.

When I click on a Link, I immediately navigate through and get a blank page until everything loads in. Better than before when things *never* loaded, but not ideal.

What I would expect to get is the usual 1 second wait before navigating, then a pending component, then my UI.

Still, I have to thank you for fixing the bug. 🙂

**Comment by freshgiammi** [comment]
I have a similar behaviour as @ArmandRedgate (and morover, my whole route tree flashes by getting remounted when the component is finished loading).

I don't think this issue has been fixed, but rather something it the route matching logic has changed and causes the route to get updated once the components are loaded.

Before, you would get an `<Outlet/>` component to be rendered as the component itself was not ready ([this](https://github.com/TanStack/router/blob/main/packages/react-router/src/Match.tsx#L232)). Once available, the Outlet however was not getting replaced with the correct component.

Now it looks like all that's changed is the component is getting updated once available, which updates the UI and makes it look like it's fixed.

If a navigation event is emitted in the timespan between the preload start and finish timestamps, this issue is almost guaranteed to happen.
Behind the scenes, I see the following:
- Preload is fired, beforeLoad is executed.
- When loader is fired, components start fetching (the route is currently in `cachedMatches`, with `{status: "pending", isFetching: "loader"}`
- If a navigation is emitted **before** the components resolve, the route gets moved to `matches` with `{status: "success", isFetching: "loader"}`, which then causes the Outlet to be rendered as the route loading is considered finished (which it isn't technically)

Something changed in [this commit](https://github.com/TanStack/router/commit/fd692cf77da2afd87d6eeed5fa3305f3a0a1a4a9) that changes the current behaviour. Additionally (might be related, since same remounting behaviour appears here), I see the whole route tree getting remounted when `router.invalidate()` is called and `wrapInSuspense` is enabled in my __root route.

**Comment by freshgiammi** [comment]
This is as close as I can get to what I'm experiencing on my project: https://stackblitz.com/edit/github-fsj9kg

I created a component that uses top-level await to mimick heavy dependencies on a route, and then used that componenent in the `/about` page. If you hover the **About** link you'll see the route in a pending state for 10s: however, if you navigate to that route in less than 10s, you'll see it get moved to `matches` but with a `success` status, even though the component hasn't finished streaming in (which I believe causes this whole ordeal).
Also, note how the pending component is never shown, unless you start browsing directly from the `/about` page itself (which loads the default pending component, even though it should be rendered anyway even while the page components fetches)

**Comment by schiller-manuel** [comment]
this will be fixed by #1907 

@freshgiammi this is your reproducer with the pre-release package: https://stackblitz.com/edit/github-fsj9kg-ndhjmk?file=package.json
