### ISSUE TITLE
Could not resolve "#tanstack-router-entry"

### ISSUE THREAD

**Issue by austinm911** [TanStack/router#5795]
### Which project does this relate to?

Start

### Describe the bug

I'm out of town this weekend but was running into this so wanted to file this bug report sooner than later. 

I'm using alchemy, which wraps `cloudflare-vite` to run tanstack start. I haven't had time to create a clean reproduction but basically what seems to be happening, is that my auth service is created as an `Effect.Service` from `effect-ts`. One of the other deps coming is is my Drizzle postgres client from `'@effect/sql-drizzle/Pg'`. 

As soon as i import `import { auth } from '@repo/core/auth/handler'` into `server.ts` or `routes/api/auth/$.ts` my app blows up with the error below. `handler.ts` imports my Runtime from effect, which has all my app dependencies, which some are required for some of the `hooks` that better auth calls in the Effectful Better Auth instance. 

Possibly related to https://github.com/vitejs/vite/issues/20867#issuecomment-3431250189. I was seeing pre-bundling issues on later versions of vite. 

The web app producing this error is a basic `better-t-stack` templated start app, with the only changes adding in alchemy and dropping in my auth into the server route. Everything starts up fine without the eventual better-auth dependency as described above.

```ts
Using vars defined in process.env
3:21:50 PM [vite] (client) Re-optimizing dependencies because lockfile has changed

  VITE v7.0.0  ready in 1097 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  Debug:   http://localhost:5173/__debug
  ➜  press h + enter to show help
[updating]  web Updating Resource...
[skipped]   web > url Skipped Resource (no changes)
[updated]   web Updated Resource
Web    -> http://localhost:5173/
✘ [ERROR] Could not resolve "#tanstack-router-entry"

    ../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:29:33:
      29 │       routerEntry = await import("#tanstack-router-entry");
         ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~

  The package import "#tanstack-router-entry" is not defined in this "imports" map:

    ../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/package.json:49:13:
      49 │   "imports": {
         ╵              ^

  You can mark the path "#tanstack-router-entry" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "#tanstack-start-entry"

    ../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:32:32:
      32 │       startEntry = await import("#tanstack-start-entry");
         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~

  The package import "#tanstack-start-entry" is not defined in this "imports" map:

    ../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/package.json:49:13:
      49 │   "imports": {
         ╵              ^

  You can mark the path "#tanstack-start-entry" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "tanstack-start-manifest:v"

    ../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:3:44:
      3 │ ...t { tsrStartManifest } = await import("tanstack-start-manifest:v");
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tanstack-start-manifest:v" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "tanstack-start-injected-head-scripts:v"

    ../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:9:49:
      9 │ ...Scripts } = await import("tanstack-start-injected-head-scripts:v");
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tanstack-start-injected-head-scripts:v" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.

3:22:06 PM [vite] (ssr) error while updating dependencies:
Error: Build failed with 4 errors:
../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:29:33: ERROR: Could not resolve "#tanstack-router-entry"
../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:32:32: ERROR: Could not resolve "#tanstack-start-entry"
../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:3:44: ERROR: Could not resolve "tanstack-start-manifest:v"
../../node_modules/.bun/@tanstack+start-server-core@1.134.15+b0d3c3aaff3e390a/node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:9:49: ERROR: Could not resolve "tanstack-start-injected-head-scripts:v"
    at failureErrorWithLog (/Users/am/Coding/redacted-projects/redacted/node_modules/.bun/esbuild@0.25.12/node_modules/esbuild/lib/main.js:1467:15)
    at /Users/am/Coding/redacted-projects/redacted/node_modules/.bun/esbuild@0.25.12/node_modules/esbuild/lib/main.js:926:25
    at /Users/am/Coding/redacted-projects/redacted/node_modules/.bun/esbuild@0.25.12/node_modules/esbuild/lib/main.js:1345:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
3:22:06 PM [vite] Internal server error: There is a new version of the pre-bundle for "/Users/am/Coding/redacted-projects/redacted/apps/web/node_modules/.vite/deps_ssr/better-auth.js?v=93306dc9", a page reload is going to ask for it.
      at CustomModuleRunner.cachedModule (workers/runner-worker.js:1236:20)
      at request (workers/runner-worker.js:1154:83)
      at null.<anonymous> (/Users/am/Coding/redacted-projects/redacted/packages/core/src/auth/setup.ts:4:1)
      at Object.runInlinedModule (workers/runner-worker.js:1337:4)
      at CustomModuleRunner.directRequest (workers/runner-worker.js:1208:59)
      at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1115:73)
      at null.<anonymous> (/Users/am/Coding/redacted-projects/redacted/packages/core/src/auth/handler.ts:2:1)
      at Object.runInlinedModule (workers/runner-worker.js:1337:4)
      at CustomModuleRunner.directRequest (workers/runner-worker.js:1208:59)
      at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1115:73)
3:22:06 PM [vite] Internal server error: There is a new version of the pre-bundle for "/Users/am/Coding/redacted-projects/redacted/apps/web/node_modules/.vite/deps_ssr/better-auth.js?v=93306dc9", a page reload is going to ask for it.
      at CustomModuleRunner.cachedModule (workers/runner-worker.js:1236:20)
      at request (workers/runner-worker.js:1154:83)
      at null.<anonymous> (/Users/am/Coding/redacted-projects/redacted/packages/core/src/auth/setup.ts:4:1)
      at Object.runInlinedModule (workers/runner-worker.js:1337:4)
      at CustomModuleRunner.directRequest (workers/runner-worker.js:1208:59)
      at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1115:73)
      at null.<anonymous> (/Users/am/Coding/redacted-projects/redacted/packages/core/src/auth/handler.ts:2:1)
      at Object.runInlinedModule (workers/runner-worker.js:1337:4)
      at CustomModuleRunner.directRequest (workers/runner-worker.js:1208:59)
      at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1115:73)
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

see above

### Expected behavior

no issues

### Platform

Vite 7.0.0
MacOS 15.6
Tanstack 1.134.15

**Comment by schiller-manuel** [comment]
please share a full reproduction project

**Comment by guillemus** [comment]
not op but I have the same error in this repo

https://github.com/guillemus/tanstack-mpa

This happened after I tried to add better auth. Maybe it is bc there's no entry-client / server files? That's what haiku suggested me but idk.

here's the full output:

```

➜  tanstack-mpa git:(main) ✗ bun dev
$ vite dev --port 3000

  VITE v7.2.2  ready in 417 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "#tanstack-router-entry"

    node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:29:33:
      29 │       routerEntry = await import("#tanstack-router-entry");
         ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~

  The package import "#tanstack-router-entry" is not defined in this "imports" map:

    node_modules/@tanstack/start-server-core/package.json:49:13:
      49 │   "imports": {
         ╵              ^

  You can mark the path "#tanstack-router-entry" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle. You can also add ".catch()"
  here to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "#tanstack-start-entry"

    node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:32:32:
      32 │       startEntry = await import("#tanstack-start-entry");
         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~

  The package import "#tanstack-start-entry" is not defined in this "imports" map:

    node_modules/@tanstack/start-server-core/package.json:49:13:
      49 │   "imports": {
         ╵              ^

  You can mark the path "#tanstack-start-entry" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle. You can also add ".catch()"
  here to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "tanstack-start-manifest:v"

    node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:3:44:
      3 │   const { tsrStartManifest } = await import("tanstack-start-manifest:v");
        ╵                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tanstack-start-manifest:v" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle. You can also add ".catch()"
  here to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "tanstack-start-injected-head-scripts:v"

    node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:9:49:
      9 │     const { injectedHeadScripts } = await import("tanstack-start-injected-head-scripts:v");
        ╵                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tanstack-start-injected-head-scripts:v" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle. You can also add
  ".catch()" here to handle this failure at run-time instead of bundle-time.

/Users/guillem/Documents/projects/tanstack-mpa/node_modules/esbuild/lib/main.js:1467
  let error = new Error(text);
              ^

Error: Error during dependency optimization:

✘ [ERROR] Could not resolve "#tanstack-router-entry"

    node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:29:33:
      29 │       routerEntry = await import("#tanstack-router-entry");
         ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~

  The package import "#tanstack-router-entry" is not defined in this "imports" map:

    node_modules/@tanstack/start-server-core/package.json:49:13:
      49 │   "imports": {
         ╵              ^

  You can mark the path "#tanstack-router-entry" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "#tanstack-start-entry"

    node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:32:32:
      32 │       startEntry = await import("#tanstack-start-entry");
         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~

  The package import "#tanstack-start-entry" is not defined in this "imports" map:

    node_modules/@tanstack/start-server-core/package.json:49:13:
      49 │   "imports": {
         ╵              ^

  You can mark the path "#tanstack-start-entry" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "tanstack-start-manifest:v"

    node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:3:44:
      3 │ ...t { tsrStartManifest } = await import("tanstack-start-manifest:v");
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tanstack-start-manifest:v" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "tanstack-start-injected-head-scripts:v"

    node_modules/@tanstack/start-server-core/dist/esm/router-manifest.js:9:49:
      9 │ ...Scripts } = await import("tanstack-start-injected-head-scripts:v");
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "tanstack-start-injected-head-scripts:v" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle this failure at run-time instead of bundle-time.


    at failureErrorWithLog (/Users/guillem/Documents/projects/tanstack-mpa/node_modules/esbuild/lib/main.js:1467:15)
    at /Users/guillem/Documents/projects/tanstack-mpa/node_modules/esbuild/lib/main.js:926:25
    at /Users/guillem/Documents/projects/tanstack-mpa/node_modules/esbuild/lib/main.js:1345:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v22.17.1
error: script "dev" exited with code 1

```

**Comment by guillemus** [comment]
@schiller-manuel I found what causes the issue somehow.

to reproduce:

- clone the repo
- rm -rf .tanstack && bun i
- you should see the error when running `bun dev`
- comment out all code from counter.ts file
- bun dev should now work.
- uncomment back the code from counter.ts
- bun dev should now work with the original code.


I hope this helps

**Comment by austinm911** [comment]
@guillemus Even adding the client/server.ts entry files, I run into the same issues as well

**Comment by theoludwig** [comment]
I have the same issue but with Vitest.

**Comment by schiller-manuel** [comment]
@theoludwig  can you share a reproducer project with vitest?

**Comment by theoludwig** [comment]
> [@theoludwig](https://github.com/theoludwig) can you share a reproducer project with vitest?

Sure, here it is: https://github.com/theoludwig/vite-nitro-issues/tree/vitest-issue

To reproduce:
1. `git clone git@github.com:theoludwig/vite-nitro-issues.git`
2. `cd vite-nitro-issues`
3. `git checkout vitest-issue`
4. `pnpm install --frozen-lockfile`
5. `node --run test`

**Comment by gianlazaro** [comment]
I'll see if I have time to make a reproducer sometime this week, but I'm having this exact issue when I install a specific library.

better-auth@beta (since 1.4 stable is coming out Friday)

**Comment by rollsrobby** [comment]
I only see this issue if I enable the `reactStartCookie` [plugin](https://www.better-auth.com/docs/integrations/tanstack#usage-tips) by better-auth.
And only after removing the node_modules folder and reinstalling(`pnpm install`). 
If I remove the plugin, clean, install. All works fine.
Maybe this observation helps..

**Comment by gianlazaro** [comment]
@rollsrobby That did the trick for me!

It got me curious and looked into what could possibly be making this issue. 

I was able to reproduce the original poster's issue by using **setCookie** imported from "@tanstack/react-start/server" (used in certain cases). I hope this narrows it down for you, @schiller-manuel 

update: I guess it's mostly affects improper uses of functions that should only run on the server like setting cookies, or headers that causes the error.

**Comment by 2bdelghafour** [comment]
@gianlazaro I ran into the same issue when using Better Auth with Tanstack Start and I can see there is already a PR open on their end to fix it by using the proper imports

https://github.com/better-auth/better-auth/pull/6045

**Comment by dotnize** [comment]
For better-auth users this has been fixed in `^1.4.1`

- https://github.com/better-auth/better-auth/pull/6209

**Comment by gianlazaro** [comment]
@dotnize @2bdelghafour 

1.4.1 fixed the issue but 1.4.2 (released a couple of hours ago) reverts back to importing start-server-core because it apparently fixes the cookies issue on with solid on tanstack start.

We're back to the same issue.

https://github.com/better-auth/better-auth/pull/6235

**Comment by theoludwig** [comment]
This is not a better-auth fix, the fix should be done in TanStack Start.

I'm not using better-auth and I also have the issue.

**Comment by amruthpillai** [comment]
Can confirm, this issue is back. I am using better-auth though, on v1.4.2

**Comment by Andresuito** [comment]
This problem has reappeared with better-auth 1.4.2

**Comment by josmartrigueiro** [comment]
I have the same problem when I use better-auth in the version 1.4.2

**Comment by amruthpillai** [comment]
Thought v1.4.3 would resolve the issue, but it hasn't. But it does seem like this is a `better-auth` issue and not a Tanstack Start/Router one, so I have created an issue over there: https://github.com/better-auth/better-auth/issues/6341

**Comment by theoludwig** [comment]
> Thought v1.4.3 would resolve the issue, but it hasn't. But it does seem like this is a `better-auth` issue and not a Tanstack Start/Router one, so I have created an issue over there: [better-auth/better-auth#6341](https://github.com/better-auth/better-auth/issues/6341)

No it is not, it can be solved in better-auth of course, with workaround, if they want to, but the root of the issue still need to be solved in TanStack Start. Also please don't spam the issues with better-auth related, it doesn't really add new information to the issue.

The issue happens, whenever, you import a module that imports `import { getCookie, setCookie } from "@tanstack/react-start/server"` in client, even if the `getCookie` or `setCookie` functions are not executed on the client.

TanStack Start, should make it so that it still works, even if you import `getCookie`/`setCookie` client side, as long, as it's not executed client side, and only executed server side.

**Comment by amruthpillai** [comment]
@theoludwig But that's an anti-pattern. Like the path to the import clearly states, `getCookie` and `setCookie` are for server-use only. Making them isomorphic or not throwing an error if they are called on the client (if someone did this intentionally) and they receive nothing, it could also cause an issue.

Better Auth would have to implement clearer separation of concerns with the functions that are importing these server-only functions. I've seen this happen in the app I'm building as well, and I can't just add a /server import anywhere in a `utils` file and expect that things should still work.

For example, doing the same thing on Next.js would throw an error like this:

<img width="988" height="514" alt="Image" src="https://github.com/user-attachments/assets/e15ad5f6-efb9-4ccc-9cdc-b8be2d2007dd" />

**Comment by dotnize** [comment]
> The issue happens, whenever, you import a module that imports `import { getCookie, setCookie } from "@tanstack/react-start/server"` in client, even if the `getCookie` or `setCookie` functions are not executed on the client.
> 
> TanStack Start, should make it so that it still works, even if you import `getCookie`/`setCookie` client side, as long, as it's not executed client side, and only executed server side.

@theoludwig I'm not sure if that's the issue with better-auth though, so I'm guessing there's more than 1 way to get this error. In better-auth's case, the error is caused by importing from `@tanstack/start-server-core` (to make it work for both solid and react) rather than directly from `@tanstack/react-start`. The fix in better-auth 1.4.1 was replacing the import with `@tanstack/react-start`.

But yeah this is most likely an issue with Start and not with better-auth.

**Comment by leonardo2204** [comment]
My workaround was basically copying the better-auth tanstack file (and adding serverOnlyFn):

```ts
import { createServerOnlyFn } from "@tanstack/react-start";
import { BetterAuthPlugin } from "better-auth";
import { createAuthMiddleware } from "better-auth/plugins";
import { parseSetCookieHeader } from "./utils";


export const tanstackStartCookie = () =>
  createServerOnlyFn(() => ({
    id: "tanstack-start-cookie",
    hooks: {
      after: [
        {
          matcher() {
            return true;
          },
          handler: createAuthMiddleware(async (ctx) => {
            const returned = ctx.context.responseHeaders;

            if ("_flag" in ctx && ctx._flag === "router") return;

            if (returned instanceof Headers) {
              const setCookies = returned?.get("set-cookie");
              if (!setCookies) return;

              const parsed = parseSetCookieHeader(setCookies);
              const { setCookie } = await import(
                "@tanstack/react-start/server"
              );

              parsed.forEach((value, key) => {
                if (!key) return;
                const opts = {
                  sameSite: value.samesite,
                  secure: value.secure,
                  maxAge: value["max-age"],
                  httpOnly: value.httponly,
                  domain: value.domain,
                  path: value.path,
                } as const;
                try {
                  setCookie(key, decodeURIComponent(value.value), opts);
                  // eslint-disable-next-line @typescript-eslint/no-unused-vars
                } catch (_) {
                  /* empty */
                }
              });
              return;
            }
          }),
        },
      ],
    },
  }))() satisfies BetterAuthPlugin;
```

```ts
interface CookieAttributes {
  value: string;
  "max-age"?: number | undefined;
  expires?: Date | undefined;
  domain?: string | undefined;
  path?: string | undefined;
  secure?: boolean | undefined;
  httponly?: boolean | undefined;
  samesite?: ("strict" | "lax" | "none") | undefined;
  [key: string]: unknown;
}

export function parseSetCookieHeader(
  setCookie: string
): Map<string, CookieAttributes> {
  const cookies = new Map<string, CookieAttributes>();
  const cookieArray = setCookie.split(", ");

  cookieArray.forEach((cookieString) => {
    const parts = cookieString.split(";").map((part) => part.trim());
    const [nameValue, ...attributes] = parts;
    const [name, ...valueParts] = (nameValue || "").split("=");

    const value = valueParts.join("=");

    if (!name || value === undefined) {
      return;
    }

    const attrObj: CookieAttributes = { value };

    attributes.forEach((attribute) => {
      const [attrName, ...attrValueParts] = attribute!.split("=");
      const attrValue = attrValueParts.join("=");

      const normalizedAttrName = attrName!.trim().toLowerCase();

      switch (normalizedAttrName) {
        case "max-age":
          attrObj["max-age"] = attrValue
            ? parseInt(attrValue.trim(), 10)
            : undefined;
          break;
        case "expires":
          attrObj.expires = attrValue ? new Date(attrValue.trim()) : undefined;
          break;
        case "domain":
          attrObj.domain = attrValue ? attrValue.trim() : undefined;
          break;
        case "path":
          attrObj.path = attrValue ? attrValue.trim() : undefined;
          break;
        case "secure":
          attrObj.secure = true;
          break;
        case "httponly":
          attrObj.httponly = true;
          break;
        case "samesite":
          attrObj.samesite = attrValue
            ? (attrValue.trim().toLowerCase() as "strict" | "lax" | "none")
            : undefined;
          break;
        default:
          // Handle any other attributes
          attrObj[normalizedAttrName] = attrValue ? attrValue.trim() : true;
          break;
      }
    });

    cookies.set(name, attrObj);
  });

  return cookies;
}

```

**Comment by AlpMimaroglu** [comment]
> [@theoludwig](https://github.com/theoludwig) But that's an anti-pattern. Like the path to the import clearly states, `getCookie` and `setCookie` are for server-use only. Making them isomorphic or not throwing an error if they are called on the client (if someone did this intentionally) and they receive nothing, it could also cause an issue.
> 
> Better Auth would have to implement clearer separation of concerns with the functions that are importing these server-only functions. I've seen this happen in the app I'm building as well, and I can't just add a /server import anywhere in a `utils` file and expect that things should still work.
> 
> For example, doing the same thing on Next.js would throw an error like this:
> <img alt="Image" width="988" height="514" src="https://private-user-images.githubusercontent.com/1134738/519438719-e15ad5f6-efb9-4ccc-9cdc-b8be2d2007dd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQzMTk1NTIsIm5iZiI6MTc2NDMxOTI1MiwicGF0aCI6Ii8xMTM0NzM4LzUxOTQzODcxOS1lMTVhZDVmNi1lZmI5LTRjY2MtOWNkYy1iOGJlMmQyMDA3ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMjhUMDg0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQwZWVhMDRiOWI0Y2QzNmZiYTc5NjA5MjEzNTQ5NWY1ODgwZDIxYWU4ZGU1NGY4ZDNmZGZkOTdiMzI0YzVlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F8qCMjGbOR8M1RIfM4-CqWDd1W1u-nk_WbHNEEoBh6I">

This is a much better error in this case. Could not resolve "#tanstack-router-entry" does not explain what the problem is at all

**Comment by stunaz** [comment]
reverted to 1.4.1 for now

**Comment by bytaesu** [comment]
Hello 🤓

This issue will be fixed in the next `better-auth` release

**Comment by FabrizzioLoPresti** [comment]
I was able to fix it temporarily in better-auth 1.4.3.
In my case, it happened with tanstackStartCookies, and I solved it by commenting out the plugin from the better-auth config, then running "rm -rf node_modules .pnpm-lock.yaml, pnpm store prune, pnpm install", and finally uncommenting the plugin.

**Comment by notKamui** [comment]
Can confirm this has been fixed as of `1.4.4`

**Comment by theoludwig** [comment]
This issue can still be reproduced with `vitest` with the repo and steps provided from this reply: https://github.com/TanStack/router/issues/5795#issuecomment-3519070764
And there are no workaround to this issue.

For example, I'm doing this:
```ts
import { getClientI18n, setClientI18nLocale } from "./i18n.client.ts"

// this uses `getCookie` and `setCookie` from `@tanstack/react-start/server`
// inside handlers of `createServerFn`, because, I'm importing it, it triggers the error
// even if I try to import them dynamically (inside the handler), it throws the same error
// const { getCookie } = await import("@tanstack/react-start/server")
import { getServerI18n, setServerI18nLocale } from "./i18n.server.ts"

// later in a React Hook or Component...
const getServerFnI18n = useServerFn(getServerI18n)

const i18nQuery = useSuspenseQuery(
  queryOptions({
    queryKey: ["i18n"],
    queryFn: shouldRunClient ? getClientI18n : getServerFnI18n,
  }),
)
```

**Comment by theoludwig** [comment]
There is the same issue when using `createIsomorphicFn`.

For example:
```ts
import { createIsomorphicFn } from "@tanstack/react-start"
import { getRequest } from "@tanstack/react-start/server"

export const getURLPath = createIsomorphicFn()
  .client(() => {
    return window.location.pathname + window.location.search
  })
  .server(() => {
    const request = getRequest()
    const url = new URL(request.url)
    return url.pathname + url.search
  })
```

```ts
│  [RESOLVE_ERROR] Error: Could not resolve '#tanstack-start-entry' in
│  ../../node_modules/.pnpm/@tanstack+start-server-core@1.149.3_crossws@0.4.1_srvx@0.9.8_/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js
│  ╭─[
│  ../../node_modules/.pnpm/@tanstack+start-server-core@1.149.3_crossws@0.4.1_srvx@0.9.8_/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js:26:35
│  ]
│  │
│  26 │   const startEntry = await import("#tanstack-start-entry");
│  │                                   ───────────┬───────────
│  │                                              ╰───────────── Package import
│  specifier is not defined
│  │
│  │ Help:
│  '../../node_modules/.pnpm/@tanstack+start-server-core@1.149.3_crossws@0.4.1_srvx@0.9.8_/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js'
│  is imported by the following path:
│  │         -
│  ../../node_modules/.pnpm/@tanstack+start-server-core@1.149.3_crossws@0.4.1_srvx@0.9.8_/node_modules/@tanstack/start-server-core/dist/esm/createStartHandler.js
│  │         -
│  ../../node_modules/.pnpm/@tanstack+start-server-core@1.149.3_crossws@0.4.1_srvx@0.9.8_/node_modules/@tanstack/start-server-core/dist/esm/index.js
│  │         -
│  ../../node_modules/.pnpm/@tanstack+react-start-server@1.149.3_crossws@0.4.1_srvx@0.9.8__react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/@tanstack/react-start-server/dist/esm/index.js
│  │         -
│  ../../node_modules/.pnpm/@tanstack+react-start@1.149.4_crossws@0.4.1_srvx@0.9.8__react-dom@19.2.3_react@19.2.3___33f76de6bc3f59c7a60113b7339ac541/node_modules/@tanstack/react-start/dist/esm/server.js
│  ────╯
```

This throws inside Storybook/Vitest for example.

(I guess, that `createIsomorphicFn` is something that "change" the vite build output with the help of `tanstackStart` vite plugin which we have to disable to make vitest/storybook tooling work and that's why there is the error: https://github.com/TanStack/router/discussions/655#discussioncomment-14836507)

**Comment by schiller-manuel** [comment]
@theoludwig createIsomorphicFn and many other things rely on the Start vite plugin. so this cannot work

**Comment by vincentparrett** [comment]
This issue reared it's head again today - tanstack start with better-auth, email/pwd auth.

I have 
@tanstack/xxx 1.140.5
better-auth 1.4.12

updating better auth to 1.4.13, or updating @tanstack/xxx to 1.150.0, or updating both results in this error 

Edit: I tried using the latest beta of better-auth, same issue. 

It's not clear if this is a tanstack issue or better-auth?

**Comment by dotnize** [comment]
@vincentparrett better-auth issue in that case. This might be fixed by this PR:

- https://github.com/better-auth/better-auth/pull/7446

But not released yet. Maybe in 1.4.15 when it's out.

This is the third time this issue has resurfaced, repeatedly caused by the same or similar PRs on their side attempting to support both Solid and React versions of tanstack start:

1. https://github.com/better-auth/better-auth/pull/6045
2. https://github.com/better-auth/better-auth/pull/6235
3. https://github.com/better-auth/better-auth/pull/7340

EDIT: fixed in better-auth `1.4.15`, you don't need any workarounds

**Comment by vincentparrett** [comment]
@dotnize thanks, I reverted and will wait to update. What is strange is I also see this if I update tanstack only.

**Comment by web-dev-sayantan** [comment]
Facing the same issue with @tanstack/* 1.150.0 and better-auth 1.4.13 in my repo, 
Opus 4.5 went on a crazy run, and fixed it for now with bunch of weird config in vite.config.ts, half of which I don't understand.


```typescript
import { defineConfig } from 'vite'
import { tanstackStart } from '@tanstack/react-start/plugin/vite'
import viteReact from '@vitejs/plugin-react'
import viteTsConfigPaths from 'vite-tsconfig-paths'
import tailwindcss from '@tailwindcss/vite'
import { cloudflare } from '@cloudflare/vite-plugin'
import type { Plugin as EsbuildPlugin } from 'esbuild'

// Plugin to mark TanStack Start virtual modules as external
const tanstackExternalPlugin: EsbuildPlugin = {
  name: 'tanstack-external',
  setup(build) {
    build.onResolve({ filter: /^#tanstack-|^tanstack-start-/ }, () => ({
      external: true,
    }))
  },
}

export default defineConfig({
  server: {
    port: 3000,
  },
  plugins: [
    tailwindcss(),
    viteTsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
    cloudflare({
      viteEnvironment: { name: 'ssr' },
      inspectorPort: false,
    }),
    tanstackStart(),
    viteReact(),
  ],
  optimizeDeps: {
    esbuildOptions: {
      plugins: [tanstackExternalPlugin],
    },
  },
  environments: {
    ssr: {
      optimizeDeps: {
        esbuildOptions: {
          plugins: [tanstackExternalPlugin],
        },
      },
    },
  },
  build: {
    rollupOptions: {
      external: ['cloudflare:workers'],
    },
  },
})

```

**Comment by ludusrusso** [comment]
> @tanstack/* 1.150.0 and better-auth 1.4.13 in my repo

same here

**Comment by joshymcd** [comment]
I was just having this issue.
For me excluding my Tanstack packages from Vites dev server optimisations seemed to do the trick 


> vite.config.ts
```ts 
  optimizeDeps: {
    // Exclude TanStack Start packages from Vite's dependency optimization
    // to prevent issues with virtual imports (#tanstack-router-entry, etc.)
    exclude: [
      '@tanstack/start-server-core',
      '@tanstack/react-start',
      '@tanstack/react-start/client',
      '@tanstack/react-start/server',
    ],
  },
```

**Comment by williiam-tran** [comment]
> I was just having this issue. For me excluding my Tanstack packages from Vites dev server optimisations seemed to do the trick
> 
> > vite.config.ts
> 
>   optimizeDeps: {
>     // Exclude TanStack Start packages from Vite's dependency optimization
>     // to prevent issues with virtual imports (#tanstack-router-entry, etc.)
>     exclude: [
>       '@tanstack/start-server-core',
>       '@tanstack/react-start',
>       '@tanstack/react-start/client',
>       '@tanstack/react-start/server',
>     ],
>   },

This works for me!

**Comment by kusalkalinga00** [comment]
> I was just having this issue. For me excluding my Tanstack packages from Vites dev server optimisations seemed to do the trick
> 
> > vite.config.ts
> 
>   optimizeDeps: {
>     // Exclude TanStack Start packages from Vite's dependency optimization
>     // to prevent issues with virtual imports (#tanstack-router-entry, etc.)
>     exclude: [
>       '@tanstack/start-server-core',
>       '@tanstack/react-start',
>       '@tanstack/react-start/client',
>       '@tanstack/react-start/server',
>     ],
>   },

This worked for me also. Issue started to originate when I migrate from bun to pnpm.

**Comment by rgripper** [comment]
> I was just having this issue. For me excluding my Tanstack packages from Vites dev server optimisations seemed to do the trick
> 
> > vite.config.ts
> 
>   optimizeDeps: {
>     // Exclude TanStack Start packages from Vite's dependency optimization
>     // to prevent issues with virtual imports (#tanstack-router-entry, etc.)
>     exclude: [
>       '@tanstack/start-server-core',
>       '@tanstack/react-start',
>       '@tanstack/react-start/client',
>       '@tanstack/react-start/server',
>     ],
>   },

didnt help, I still have the same error

**Comment by astralarya** [comment]
I started getting similar errors upgrading from 1.149.1 -> 1.151.1, which I was able to resolve by adding this to my vite config:
```json
  optimizeDeps: {
    exclude: [
      "@tanstack/start-server-core",
      "@tanstack/start-client-core",
      "@tanstack/react-start",
    ],
  },
```

On one hand, I'm glad that this fixes it, but on the other hand, I wish it weren't necessary.

**Comment by bytaesu** [comment]
from Better Auth,
We've worked on this, I tested it in the actual app, and I can confirm that it's fixed now in `v1.4.15` 😄

- https://github.com/better-auth/better-auth/pull/7446

**Comment by MarcusGasberg** [comment]
Weirdly enough I still encountered it after upgrading, when I tried to deploy to Cloudflare workers. The issue was due to having multiple environments in my wrangler.toml and not passing the correct CLOUDFLARE_ENV to my build command. I also had to point to the generated wrangler.json file.

**Previous build command:**
```
    "deploy:staging": "bun run build && bunx wrangler deploy --env=\"staging\" --keep-vars --config ./wrangler.toml",\
```
**Fixed:** 
```
   "deploy:staging": "CLOUDFLARE_ENV=staging bun run build && bunx wrangler deploy --keep-vars --config ./dist/server/wrangler.json",
```

**Comment by isc30** [comment]
> I started getting similar errors upgrading from 1.149.1 -> 1.151.1, which I was able to resolve by adding this to my vite config:
> 
>   optimizeDeps: {
>     exclude: [
>       "@tanstack/start-server-core",
>       "@tanstack/start-client-core",
>       "@tanstack/react-start",
>     ],
>   },
> On one hand, I'm glad that this fixes it, but on the other hand, I wish it weren't necessary.

is this the properly-done-accepted way or just a hack?

**Comment by isc30** [comment]
For the proper solution, see https://github.com/better-auth/better-auth/pull/6045#issuecomment-3557364403
Basically, replace the imports from `@tanstack/react-start-server` to `@tanstack/react-start/server` and vite will be happy.

I believe this would be a good addition to the eslint plugin, to inform users to use the proper import to avoid vite dependency optimization issues.

**Comment by barbalex** [comment]
Not sure if this is the same issue: In an app using tanstack router I tried to use tanstack start (to add server routes). When replacing `TanStackRouterVite({ target: 'react', autoCodeSplitting: true })` with `tanstackStart()` I immediately get this error:
```console
TypeError: entries.routerEntry.getRouter is not a function
    at getRouter (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:472:44)
    ... 8 lines matching cause stack trace ...
    at async Object.fetch (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/react-start/dist/plugin/default-entry/server.ts:16:14) {
  cause: TypeError: entries.routerEntry.getRouter is not a function
      at getRouter (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:472:44)
      at handleServerRoutes (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:724:24)
      at eval (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:606:28)
      at AsyncLocalStorage.run (node:internal/async_local_storage/async_context_frame:63:14)
      at runWithStartContext (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-storage-context/src/async-local-storage.ts:34:23)
      at requestHandlerMiddleware (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:596:16)
      at next (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:279:22)
      at executeMiddleware (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:301:10)
      at startRequestResolver (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/start-server-core/src/createStartHandler.ts:627:25)
      at async Object.fetch (/home/alex/Documents/GitHub/ps/node_modules/@tanstack/react-start/dist/plugin/default-entry/server.ts:16:14),
  status: 500,
  statusText: undefined,
  headers: undefined,
  data: undefined,
  body: undefined,
  unhandled: true
}
```

**Comment by escwxyz** [comment]
Same error for basic start example with RSC, no better-auth, vite 8.

Repro: https://github.com/escwxyz/tanstack-rsc-test


<img width="533" height="841" alt="Image" src="https://github.com/user-attachments/assets/fb51d875-f8e6-4f1c-84c9-15e4e179e89b" />
