### ISSUE TITLE
Solid: bad <Link> performance on large datasets

### ISSUE THREAD

**Issue by teidesu** [TanStack/router#5823]
### Which project does this relate to?

Router

### Describe the bug

when rendering a lot of `<Link>`s at once, some take up to 8ms to render, resulting in ui stutters

<img width="357" height="195" alt="Image" src="https://github.com/user-attachments/assets/c02a70ab-3a26-4958-afe9-86baf51dcbe6" />

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-q4irqygh

### Steps to Reproduce the Bug or Issue

1. open the linked repro
2. click "show many"
3. notice how it takes a bit of time for stuff to render
4. try replacing tanstack router links with simple manual `<a>` links, notice how everything becomes instant

https://github.com/user-attachments/assets/3726e37f-7dd3-4878-bbf8-f0238cf041d9

### Expected behavior

i expect tanstack router to not have that much of overhead over manual `<a>` elements with an `onClick`

### Platform

- Router / Start Version: 1.135.2
- OS: macOS (M3 Max)
- Browser: Chrome
- Browser Version: 141
- Bundler: vite
- Bundler Version: 7.2.2

### Additional context

trace from chrome performance tab: [Trace-20251112T014637.json](https://github.com/user-attachments/files/23487477/Trace-20251112T014637.json)

**Comment by schiller-manuel** [comment]
is this only on solid? or does this affect react as well

**Comment by teidesu** [comment]
not sure, i didn't test, i dont use react :c

**Comment by birkskyum** [comment]
@schiller-manuel  I ported the repro to React, which show the same behavior
- https://stackblitz.com/~/github.com/birkskyum/tanstack-router-many-link-stutter?file=package.json
- https://github.com/birkskyum/tanstack-router-many-link-stutter

**Comment by schiller-manuel** [comment]
i am not surprised that this is not a solid issue. a Link does much more work, e.g. checking whether it is active. for this we need to perform route matching.

this might get sped up by this PR: https://github.com/TanStack/router/pull/5722

when this landed we should revisit and benchmark to identify the (remaining) bottlenecks

**Comment by Sheraff** [comment]
@teidesu we just merged a performance improvement of the routing itself (not of the Link component). Would you mind getting another performance trace to asses the remaining issues?

**Comment by teidesu** [comment]
updated the solid repro to 1.136.5
https://stackblitz.com/edit/vitejs-vite-n9tipj8u
(not sure how to make a fork of that react one without making a github repo :c)

doesn't feel like it improved a ton :c

traces:

- solid: [Trace-20251115T181926.json.gz](https://github.com/user-attachments/files/23562288/Trace-20251115T181926.json.gz)
- react: [Trace-20251115T182434-react.json.gz](https://github.com/user-attachments/files/23562289/Trace-20251115T182434-react.json.gz)

**Comment by Sheraff** [comment]
Are you running the traces on a built app? Or in dev mode?

**Comment by teidesu** [comment]
those were in dev, though in prod the issue persists

traces from prod build (with `minify: false`, `vite build && node start.js` in repro): 

[Trace-20251115T191237.json.gz](https://github.com/user-attachments/files/23562548/Trace-20251115T191237.json.gz)

**Comment by kompot** [comment]
Probable path to optimise — update only 2 links immediately. Previous one and next one. And try to defer updating all others.

**Comment by schiller-manuel** [comment]
we recently optimized link performance so its worth checking this again

**Comment by brenelz** [comment]
Any update here?
