### ISSUE TITLE
Beta.87 Link Path Changes but Page Content Fails to Load

### ISSUE THREAD

**Issue by bachiitter** [TanStack/router#597]
### Describe the bug

The bug is causing a problem where clicking on a link does not load the content of the requested page, even though the link path changes correctly. 

### Your Example Website or App

https://e4296ea1.dayplanr.pages.dev/

### Steps to Reproduce the Bug or Issue

To reproduce go to example website and click Privacy Policy link, path will change to /privacy but content will be not update.

### Expected behavior

On clicking Link content for /privacy page should load.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jintaokoong** [comment]
After you click the link to privacy policy and click on the link to home, the privacy policy page shows. Seems like the rendering is lagging behind by one.

**Comment by bachiitter** [comment]
> After you click the link to privacy policy and click on the link to home, the privacy policy page shows. Seems like the rendering is lagging behind by one.

It's either you click another like or full page refresh

**Comment by tannerlinsley** [comment]
Try the latest beta version.

Tanner Linsley

**Comment by hosmelq** [comment]
Still not working for me in the latest beta (89).

https://user-images.githubusercontent.com/1166143/236847172-00108e01-91ea-44cb-a16f-a5aa536bb1aa.mp4

**Comment by tannerlinsley** [comment]
I’ll check it out soon.

Tanner Linsley

**Comment by bsell93** [comment]
@tannerlinsley able to reproduce with the code from ["Quick Start"](https://tanstack.com/router/v1/docs/quick-start)
https://codesandbox.io/s/romantic-babycat-nuk2qh?file=/src/index.tsx

**Comment by bachiitter** [comment]
> I’ll check it out soon.
> 
> Tanner Linsley
> On May 8, 2023 at 8:14 AM -0600, Hosmel Quintana ***@***.***>, wrote:
> > Still not working for me in the latest beta (89).
> > https://user-images.githubusercontent.com/1166143/236847172-00108e01-91ea-44cb-a16f-a5aa536bb1aa.mp4
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you commented.Message ID: ***@***.***>
> 

Tested on Basic Example bug is still there.

**Comment by janek26** [comment]
Same issue.

Until then use the latest version without the issue:
```diff
// package.json
-     "@tanstack/router": "0.0.1-beta.89",
+     "@tanstack/router": "0.0.1-beta.86",
```

**Comment by AndrewOttavianoAbb** [comment]
Can confirm this happens with the `useNavigate` hook as well in a simple CRA app.

**Comment by tansanDOTeth** [comment]
Just going to leave a comment with "click twice" to help surface this issue for other people

**Comment by bhaugeea** [comment]
This appears to be fixed in `beta.86`. All the other surrounding versions don't seem to work.

**Comment by enrique-ramirez** [comment]
Just adding a comment to resurface this issue since this is a rather critical bug that almost made our team switch to a different router. I downgraded for now, but this issue is rather critical so leaving my +1 here.

**Comment by hosmelq** [comment]
I have to downgrade too 😭

**Comment by marcusgchan** [comment]
It seems to be affecting the examples in the docs too: https://tanstack.com/router/v1/docs/examples/react/basic?file=src%2Fmain.tsx

**Comment by tansanDOTeth** [comment]
Looking at the diff between 86 and 87. I'm guessing this line broke it?

https://github.com/TanStack/router/compare/v0.0.1-beta.86...v0.0.1-beta.87#diff-850c78d21b05a5a190d7c52fe48c75ad119c26628103343a0963d93ebffc6036L49

**Comment by RyanIgo** [comment]
any eta on when this will be fixed?

**Comment by usmanabdurrehman** [comment]
Kindly fix it asap. I was preparing the material for a tutorial I was working on for this and stumbled across this.

**Comment by tannerlinsley** [comment]
Fixed in latest.

**Comment by tannerlinsley** [comment]
> Kindly fix it asap. I was preparing the material for a tutorial I was working on for this and stumbled across this.

FYI, just because you put "kindly" in front of an imperative statement, doesn't make it any less of a demand that you are generally not allowed to make in OSS.

**Comment by usmanabdurrehman** [comment]
> > Kindly fix it asap. I was preparing the material for a tutorial I was working on for this and stumbled across this.
> 
> FYI, just because you put "kindly" in front of an imperative statement, doesn't make it any less of a demand that you are generally not allowed to make in OSS.

I am sorry. I was saying it in goodwill because I liked this library and I didn't want someone to use it and then abandon it because of this. The `asap` was because pretty sure the fix for this would have been simple. Sorry again. The intention wasn't wrong. I was/am actually thinking of contributing to tanstack as well(if now you would allow me to xd).

**Comment by tansanDOTeth** [comment]
> Fixed in latest.

Yes!! Thank you!

**Comment by 27leaves** [comment]
> Fixed in latest.

Just to be clear on "latest" - `yarn add @tanstack/router@beta` still gives me `0.0.1-beta.89`, on which I still experience the issue in. So this wasn't released yet, right?

**Comment by pawelblaszczyk5** [comment]
> > Fixed in latest.
> 
> Just to be clear on "latest" - `yarn add @tanstack/router@beta` still gives me `0.0.1-beta.89`, on which I still experience the issue in. So this wasn't released yet, right?

Yup, it seems like the GitHub action that publishes it failed

**Comment by tannerlinsley** [comment]
Yeah I need to fix the action. The latest commit for sure has the fix.

Tanner Linsley

**Comment by Sawtaytoes** [comment]
I came from the other thread on this same issue.

I've tried a number of versions, all have the same issue.

How do I get that latest commit with the fix?

**Comment by tansanDOTeth** [comment]
> I came from the other thread on this same issue. After hours of trying to figure this out, I gave up and determined its probably a library issue. Wish I would've found this thread sooner.
> 
> I've tried a number of versions and all have the same issue from .53 to .89.
> 
> How do I get that latest commit with the fix?

Looks like the tag has not been published yet. You can target the latest commit.

**Comment by Sawtaytoes** [comment]
What's the syntax for `package.json`?

This is what I did:
```json
    "@tanstack/router": "github:TanStack/router",
```

This is the output Yarn gave me:
```sh
yarn
➤ YN0000: ┌ Resolution step
➤ YN0013: │ @tanstack/router@https://github.com/TanStack/router.git#commit=ed3eb904da0ee35
➤ YN0013: │ @tanstack/router@https://github.com/TanStack/router.git#commit=ed3eb904da0ee35 
➤ YN0001: │ Error: @tanstack/router@https://github.com/TanStack/router.git#commit=ed3eb904da0ee35cdadefbf879ec7a0d091b0bd4: Assertion failed: Unsupported workflow
```

**Comment by Sawtaytoes** [comment]
Finally fixed it! It was an issue in `@tanstack/store`.

I made the change 4 times until I found the right file for my use case. I have ESM, so this is where I found it:
![image](https://github.com/TanStack/router/assets/3948069/bdb413d6-b1c2-4898-b820-62021dde82a2)

I ran `yarn patch @tanstack/store`, copied in my changes, and ran `yarn patch-commit -s "DIRECTORY"`. Yarn gave me this command. It's just a copy-paste.

Here's the diff:
```diff
diff --git a/build/esm/index.js b/build/esm/index.js
index 8d82b5e3e7189e89feb5d4026a741532f41abacf..7d0c04202da71fae01d6027f3082f5c5f5496740 100644
--- a/build/esm/index.js
+++ b/build/esm/index.js
@@ -15,9 +15,6 @@ class Store {
   constructor(initialState, options) {
     this.state = initialState;
     this.options = options;
-    if (this.options?.onUpdate) {
-      this.subscribe(this.options?.onUpdate);
-    }
   }
   subscribe = listener => {
     this.listeners.add(listener);
@@ -30,6 +27,11 @@ class Store {
   setState = updater => {
     const previous = this.state;
     this.state = this.options?.updateFn ? this.options.updateFn(previous)(updater) : updater(previous);
+
+    // Always run onUpdate, regardless of batching
+    this.options?.onUpdate?.()
+
+    // Attempt to flush
     this.#flush();
   };
   #flush = () => {
```
